artifact_location: /mnt/Data/Long-Data/cigarette-detection-using-yolov12-and-sahi/runs/mlflow/214674803281873757
creation_time: 1763138090478
experiment_id: '214674803281873757'
last_update_time: 1763138090478
lifecycle_stage: active
name: /Shared/Ultralytics
