artifact_location: /mnt/Data/Long-Data/cigarette-detection-using-yolov12-and-sahi/runs/mlflow/0
creation_time: 1763138090460
experiment_id: '0'
last_update_time: 1763138090460
lifecycle_stage: active
name: Default
